function rs = saveResults(results)
  fid = [];
    if (exist([pwd filesep 'resultsHSNOE.csv'], 'file') == 0)
        fid = fopen([pwd filesep 'resultsHSNOE.csv'], 'w');
        fprintf(fid, '%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s\n', ...
           'Data Set', 'initial_acc','fs_test_acc', 'fs_test_auc', 'fs_test_auprc', 'fs_test_fscore', 'fs_test_gmean', ...
          'unop_batest_acc', 'unop_batest_auc', 'unop_batest_auprc', 'unop_batest_fscore', 'unop_batest_gmean',...
          'unop_ortest_acc', 'unop_ortest_auc', 'unop_ortest_auprc', 'unop_ortest_fscore', 'unop_ortest_gmean',...
          'op_batest_acc', 'op_batest_auc', 'op_batest_auprc', 'op_batest_fscore', 'op_batest_gmean',...
          'op_ortest_acc', 'op_ortest_auc', 'op_ortest_auprc', 'op_ortest_fscore', 'op_ortest_gmean',...
          'be_op_test_acc', 'be_op_test_auc', 'be_op_test_auprc', 'be_op_test_fscore', 'be_op_test_gmean');
    elseif (exist([pwd filesep 'resultsHSNOE.csv'], 'file') == 2)
        fid = fopen([pwd filesep 'resultsHSNOE.csv'], 'a');
    end
    fprintf(fid, '%s, ', results.p_name);
    fprintf(fid, '%f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f\n', ...
          results.initial_acc, results.fs_test_acc, results.fs_test_auc, results.fs_test_auprc, results.fs_test_fscore, results.fs_test_gmean, ...
          results.unop_batest_acc, results.unop_batest_auc, results.unop_batest_auprc, results.unop_batest_fscore, results.unop_batest_gmean, ...
          results.unop_ortest_acc, results.unop_ortest_auc , results.unop_ortest_auprc , results.unop_ortest_fscore, results.unop_ortest_gmean, ...
          results.op_batest_acc, results.op_batest_auc , results.op_batest_auprc , results.op_batest_fscore, results.op_batest_gmean, ...
          results.op_ortest_acc, results.op_ortest_auc , results.op_ortest_auprc , results.op_ortest_fscore, results.op_ortest_gmean, ...
          results.be_op_test_acc, results.be_op_test_auc , results.be_op_test_auprc , results.be_op_test_fscore, results.be_op_test_gmean);
    fclose(fid);
end
