function rs = saveResults(results)
  fid = [];
    if (exist([pwd filesep 'results.csv'], 'file') == 0)
        fid = fopen([pwd filesep 'results.csv'], 'w');
        fprintf(fid, '%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s\n', ...
           'Data Set', 'initial_acc', 'fs_training_acc', 'fs_training_auc', 'fs_training_auprc', 'fs_training_fscore',...
          'fs_test_acc', 'fs_test_auc', 'fs_test_auprc', 'fs_test_fscore', 'op_training_acc', 'op_training_auc',...
          'op_training_auprc', 'op_training_fscore', 'unop_training_acc', 'unop_training_auc', 'unop_training_auprc',...
          'unop_training_fscore', 'op_test_acc', 'op_test_auc', 'op_test_auprc', 'op_test_fscore');
    elseif (exist([pwd filesep 'results.csv'], 'file') == 2)
        fid = fopen([pwd filesep 'results.csv'], 'a');
    end
    fprintf(fid, '%s, ', results.p_name);
    fprintf(fid, '%f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f, %f\n', ...
          results.initial_acc, results.fs_training_acc, results.fs_training_auc, results.fs_training_auprc, results.fs_training_fscore,...
          results.fs_test_acc, results.fs_test_auc, results.fs_test_auprc, results.fs_test_fscore, results.op_training_acc, results.op_training_auc,...
          results.op_training_auprc, results.op_training_fscore, results.unop_training_acc, results.unop_training_auc, results.unop_training_auprc,...
          results.unop_training_fscore, results.op_test_acc , results.op_test_auc , results.op_test_auprc, results.op_test_fscore);
    fclose(fid);
end



